---
galaxy_info:
  author: Philipp Wahala
  description: Install local packages on your mac
  license: MIT
  min_ansible_version: 1.2
  platforms:
  - name: MacOSX
    versions:
    - 10.9
    - 10.10
  categories:
  - development
  - packaging
