---
- hosts: all
  tasks:
    # - shell: chsh -s `which zsh`
    - command: chflags hidden "{{ item }}"
      sudo: yes
      # args:
        # chdir: /Applications/
      with_items:
        - "/Applications/Chess.app"
        - "/Applications/Dashboard.app"
        - "/Applications/Dictionary.app"
        - "/Applications/DVD Player.app"
        - "/Applications/Game Center.app"
        - "/Applications/Maps.app"
        - "/Applications/Photo Booth.app"
        - "/Applications/QuickTime Player.app"
        - "/Applications/Stickies.app"
