---
- name: Mount {{ app_name }} image
  command: hdiutil attach "{{ app_path }}"
- name: Remove existing app if present
  file: path="/Applications/{{ app_name }}.app" state=absent
  when: installer_type == 'app'
- name: Copy {{ app_name }} app to Applications directory
  command: cp -R "{{ mount_path }}{{ app_name }}.app" /Applications
  when: installer_type == 'app'
- name: Install {{ app_name }} pkg
  command: sudo installer -package "{{ mount_path }}{{ app_name }}.pkg" -target {{ install_target }}
  when: installer_type == 'pkg'
- name: Unmount {{ app_name }} image
  command: hdiutil detach "{{ mount_path }}"

